project_name: blink-cli
builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -mod=vendor
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "user/repo"
      - "user/repo:{{ .Tag }}"
    skip_push: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'