# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.3.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.18/blink_0.3.18_darwin_arm64.tar.gz"
      sha256 "aa21acea307b2203453fbac2e96f03f696dc49363fb2e163bcb29333c36eefeb"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.18/blink_0.3.18_darwin_amd64.tar.gz"
      sha256 "0ddc770522a0f87ea9e7c122ace17de8176bc3d425084a4e96b77f17795b19c5"

      def install
        bin.install "blink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.18/blink_0.3.18_linux_amd64.tar.gz"
      sha256 "2ae30e0db97865dafdfab733673b58ce4f57f8da9da091a84684633569925279"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.18/blink_0.3.18_linux_arm64.tar.gz"
      sha256 "cb6c55d398ff836384461e8b4035c81d721b559e72c235cb5788fae420fa8cc5"

      def install
        bin.install "blink"
      end
    end
  end
end
