# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlinkCli < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.6/blink-cli_0.1.6_darwin_arm64.tar.gz"
      sha256 "e26c0bef9b63a7b01b402953da285b6d080b7081a5d76d812c341bf99d1341d5"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.6/blink-cli_0.1.6_darwin_amd64.tar.gz"
      sha256 "8b4c925e40fb094c8db09020df60965a8b1b2824ea3894607faa4f2df89637bb"

      def install
        bin.install "blink-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.6/blink-cli_0.1.6_linux_arm64.tar.gz"
      sha256 "7b17e45009c7a187a391489a43000efc4b271eb9e50d20f04c0ad561dfb966bf"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.6/blink-cli_0.1.6_linux_amd64.tar.gz"
      sha256 "413d1501a48e78da05cbf0a8e5c780de0a695b709f049e55c135c1217be94e04"

      def install
        bin.install "blink-cli"
      end
    end
  end
end
