# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlinkCli < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.2/blink-cli_0.3.2_darwin_amd64.tar.gz"
      sha256 "19e98e9883a97cb64e9b0035df0ba4ad49f6bd9903aa2d2e6ddac9a97ea69e9b"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.2/blink-cli_0.3.2_darwin_arm64.tar.gz"
      sha256 "120be0875b67b721db27cf025c9605615e9fb7126f13f6f3fa24d0b4a7508453"

      def install
        bin.install "blink-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.2/blink-cli_0.3.2_linux_amd64.tar.gz"
      sha256 "78254b38dba96c83443e234b0180e38081929072a42eaf7c28c8a35abd09c31b"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.2/blink-cli_0.3.2_linux_arm64.tar.gz"
      sha256 "bf94a04d53cd0b85e7cd53ad12db5d2f393bbd7f1affee51f8334c27c8f0de13"

      def install
        bin.install "blink-cli"
      end
    end
  end
end
