# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlinkCli < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.4/blink-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "500a56fea826dce1674c2e1d6d3211d6520ffc1b7bbdf2e7668d899798f399cf"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.4/blink-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "f9ca7b5c8a36b86d0ea427665b9d939840a84abd53b1751ac6eae7b00b939624"

      def install
        bin.install "blink-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.4/blink-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "2c6688a51ba0684ce2c6764113e217237202450e9848421553cd84270b4e9cf0"

      def install
        bin.install "blink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.1.4/blink-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "4b41a40264a1719ac2214af18f7014a26e0f3f87e015e452889d3e20f4f0c6ad"

      def install
        bin.install "blink-cli"
      end
    end
  end
end
