# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.3.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.20/blink_0.3.20_darwin_arm64.tar.gz"
      sha256 "67e9bcb14281cbb137f6446b2dddbf7d1312159f5279a35805c5576830246d30"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.20/blink_0.3.20_darwin_amd64.tar.gz"
      sha256 "ff0215453a67d3477b8d284dbd51b65144fec87365d87f6941c4647a37ca4467"

      def install
        bin.install "blink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.20/blink_0.3.20_linux_arm64.tar.gz"
      sha256 "a3622ccc10427384003012bcbf5a2ccfbb1bd68f2dc64a4785fc1de3634e3e4c"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.20/blink_0.3.20_linux_amd64.tar.gz"
      sha256 "8a19322d672b1b1425c8dd00951684f2f081967c2392177a495299224049077f"

      def install
        bin.install "blink"
      end
    end
  end
end
