# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blink < Formula
  desc "Awesome CLI for the blink ops platform"
  homepage "https://www.blinkops.com/"
  version "0.3.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.21/blink_0.3.21_darwin_amd64.tar.gz"
      sha256 "89b4cd9b141c3e3b4e264c367ac3fa9935faaabdfbfeb7034344760dad026d77"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.21/blink_0.3.21_darwin_arm64.tar.gz"
      sha256 "7ee308ed889280e938abbd3cfb9856ba4e788098bbfa254721d599a5af26ccce"

      def install
        bin.install "blink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.21/blink_0.3.21_linux_amd64.tar.gz"
      sha256 "da74be3809757807a8867d8b6da590cdef2ef074d2141a101cc0f6b2a3fe2c00"

      def install
        bin.install "blink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blinkops/blink-go-cli/releases/download/v0.3.21/blink_0.3.21_linux_arm64.tar.gz"
      sha256 "3704a82645c20bfbc325f91d6ae324f62cd743d9ff426bf26bb95d7f61d099ab"

      def install
        bin.install "blink"
      end
    end
  end
end
