package normalizer

import (
	"fmt"
	"strings"

	"github.com/spf13/pflag"

	"github.com/go-openapi/loads"

	"github.com/blinkops/blink-go-cli/pkg/consts"

	"github.com/blinkops/blink-go-cli/pkg/utils"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// Separate between global and command flags.

type FlagNormalizer struct {
	doc *loads.Document
}

func NewFlagNormalizer(doc *loads.Document) *FlagNormalizer {
	return &FlagNormalizer{
		doc: doc,
	}
}

// Normalize Normalizes the cobra flags
func (normalizer *FlagNormalizer) Normalize(root *cobra.Command) {

	// disable this stuff
	for _, flag := range []string{consts.ApiKeyHeader, consts.SchemeEntry} {
		flag := root.PersistentFlags().Lookup(flag)
		if flag != nil {
			flag.Hidden = true
		}
	}

	root.PersistentFlags().String(consts.ApiKeyFlagName, "", "")

	root.PersistentPreRunE = normalizer.bindFlags

	for _, val := range root.Commands() {
		for _, subCommands := range val.Commands() {
			ws := subCommands.PersistentFlags().Lookup(consts.WorkspaceIDAutoGenFlagName)
			if ws != nil {
				subCommands.PersistentFlags().String(consts.WorkspaceNameFlagName, "", "workspace name")
				// bindWorkspace needs to run after the global flags are parsed
				// but before the command is run
				ws.Changed = true
				ws.Hidden = true
			}
		}
	}
}

func (normalizer *FlagNormalizer) bindFlags(cmd *cobra.Command, _ []string) (err error) {
	err = normalizer.enforceRequired(cmd)
	if err != nil {
		return err
	}
	apiKey := normalizer.setAPIKey(cmd)
	err = normalizer.setWorkspace(cmd, apiKey)
	if err != nil {
		return nil
	}
	return nil
}

func (normalizer *FlagNormalizer) enforceRequired(cmd *cobra.Command) (err error) {

	requiredError := false
	flagName := ""

	cmd.Flags().VisitAll(func(flag *pflag.Flag) {
		if strings.HasPrefix(flag.Usage, "Required.") {
			if !flag.Changed {
				requiredError = true
				flagName = flag.Name
			}
		}
	})
	if requiredError {
		return fmt.Errorf("Required flag `" + flagName + "` has not been set")
	}
	return nil

}

func (normalizer *FlagNormalizer) setAPIKey(cmd *cobra.Command) (apiKeyStr string) {
	apiKey := cmd.Root().PersistentFlags().Lookup(consts.ApiKeyFlagName)
	if apiKey != nil && apiKey.Value.String() != "" {
		apiKeyStr = apiKey.Value.String()
		// set this, so later it can be read from the autogenerated cli
		viper.Set(consts.ApiKeyHeader, apiKeyStr)
	} else {
		apiKeyStr = viper.GetString(consts.APIKeyCobraKey)
	}
	return apiKeyStr
}

func (normalizer *FlagNormalizer) setWorkspace(cmd *cobra.Command, apiKeyStr string) (err error) {
	workspaceName := cmd.PersistentFlags().Lookup(consts.WorkspaceNameFlagName)
	// Take care of resolving workspace
	var workspaceID string
	//  get the workspace name from flag and resolve into id
	if workspaceName != nil && workspaceName.Value.String() != "" {
		workspaceID, err = utils.GetWorkspaceID(workspaceName.Value.String(), apiKeyStr)
		if err != nil {
			return fmt.Errorf("--api-key error obtaining workspace-id: %s", err)
		}
	} else {
		workspaceID = viper.GetString(consts.WorkspaceIDCobraKey)
	}

	ws := cmd.PersistentFlags().Lookup(consts.WorkspaceIDAutoGenFlagName)
	if ws != nil {
		if err := ws.Value.Set(workspaceID); err != nil {
			return fmt.Errorf("error occurred while setting workspace-id: %s, error: %v", workspaceID, err)
		}
	}
	return nil
}
