package normalizer

import (
	"fmt"
	"github.com/blinkops/blink-go-cli/pkg/consts"

	"github.com/blinkops/blink-go-cli/pkg/utils"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// Separate between global and command flags.

// NormalizeFlags formats the cobra flags according to the
func NormalizeFlags(root *cobra.Command) {

	// disable this stuff
	for _, flag := range []string{consts.ApiKeyHeader, consts.SchemeEntry} {
		flag := root.PersistentFlags().Lookup(flag)
		if flag != nil {
			flag.Hidden = true
		}
	}

	root.PersistentFlags().String(consts.ApiKeyFlagName, "", "")

	root.PersistentPreRunE = bindFlags

	for _, val := range root.Commands() {
		for _, subCommands := range val.Commands() {
			ws := subCommands.PersistentFlags().Lookup(consts.WorkspaceIDAutoGenFlagName)
			if ws != nil {
				subCommands.PersistentFlags().String(consts.WorkspaceNameFlagName, "", "")
				// bindWorkspace needs to run after the global flags are parsed
				// but before the command is run
				//subCommands.PersistentPreRunE = bindWorkspace
				ws.Changed = true
				ws.Hidden = true
			}
		}
	}
}

func bindFlags(cmd *cobra.Command, _ []string) (err error) {

	// look for these provided values
	workspaceName := cmd.PersistentFlags().Lookup(consts.WorkspaceNameFlagName)
	apiKey := cmd.Root().PersistentFlags().Lookup(consts.ApiKeyFlagName)
	apiKeyStr := ""

	if apiKey != nil && apiKey.Value.String() != "" {
		apiKeyStr = apiKey.Value.String()
		// set this, so later it can be read from the autogenerated cli
		viper.Set(consts.ApiKeyHeader, apiKeyStr)
	} else {
		apiKeyStr = viper.GetString(consts.APIKeyCobraKey)
	}

	// Take care of resolving workspace
	var workspaceID string
	//  get the workspace name from flag and resolve into id
	if workspaceName != nil && workspaceName.Value.String() != "" {
		workspaceID, err = utils.GetWorkspaceID(workspaceName.Value.String(), apiKeyStr)
		if err != nil {
			return fmt.Errorf("--api-key error obtaining workspace-id: %s", err)
		}
	} else {
		workspaceID = viper.GetString(consts.WorkspaceIDCobraKey)
	}

	ws := cmd.PersistentFlags().Lookup(consts.WorkspaceIDAutoGenFlagName)
	if ws != nil {
		if err := ws.Value.Set(workspaceID); err != nil {
			return fmt.Errorf("error occurred while setting workspace-id: %s, error: %v", workspaceID, err)
		}
	}

	return nil

}
