name: Push to Docker Hub on New Release

on:
  push:
    tags:
      - '*'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DH_USER}}/blink-cli:${{github.ref_name}}
    - name: Login into DockerHub
      env: 
        DOCKER_USER: ${{secrets.DH_USER}}
        DOCKER_PASSWORD: ${{secrets.DH_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push the Docker image to DockerHub
      run: docker push ${{secrets.DH_USER}}/blink-cli:${{github.ref_name}}
      
